version: '3.3'

volumes:
  postgres_data:
  static_value:

services:
  db:
    image: postgres:12.4
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
  web:
    build: .
    # image: dioni3/sprint19
    command: gunicorn api_yamdb.wsgi:application --bind 0.0.0.0:8000
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - static_value:/code/static/
    depends_on:
      - db
    env_file:
      - ./.env 

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_value:/code/static/
    depends_on:
      - web